// @lyku/para-kit — the P9 artifact emitter (plan §6, step 5).
//
// Pure core, no filesystem: `emitServerArtifacts` takes { path, source }
// pairs and returns what to write — the per-file `<name>.server.pts`
// sibling artifacts (extractServerSources' readable, ejectable module) plus
// ONE app-wide manifest module that imports every artifact and exports the
// flat source list the host consumes. The CLI (cli.js) is the thin fs shell.
//
// The moduleId handed to extractServerSources is the .pui path AS GIVEN —
// the same id para-preprocess embeds in the client binding (its `filename`),
// which is what makes client subKey ≡ host subKey. Pass route-relative
// paths consistently on both sides.

import { extractServerSources } from "@lyku/para-preprocess";

/** `src/routes/stats/+page.pui` → `src/routes/stats/+page.server-sources.pts` */
export function artifactPathFor(puiPath) {
  return puiPath.replace(/\.pui$/, ".server-sources.pts");
}

/**
 * @param {Array<{ path: string, source: string }>} files  .pui sources.
 * @param {{ manifestPath?: string }} [opts]
 * @returns {{
 *   artifacts: Array<{ path: string, code: string, forPui: string }>,
 *   manifest: { path: string, code: string },
 *   diagnostics: string[],
 * }}
 */
export function emitServerArtifacts(files, opts = {}) {
  const manifestPath = opts.manifestPath ?? "src/lib/para-sync-manifest.js";
  const artifacts = [];
  const diagnostics = [];
  const entries = [];
  for (const f of files) {
    const r = extractServerSources(f.source, { moduleId: f.path });
    for (const d of r.diagnostics) diagnostics.push(`${f.path}: ${d}`);
    if (!r.serverModule || r.sources.length === 0) continue;
    const path = artifactPathFor(f.path);
    artifacts.push({ path, code: r.serverModule, forPui: f.path });
    entries.push({ artifact: path, count: r.sources.length });
  }

  // The manifest imports each artifact's __paraServerSources and flattens.
  // Import specifiers are made manifest-relative so the emitted tree works
  // wherever the app roots it.
  const manifestDir = manifestPath.split("/").slice(0, -1).join("/");
  const rel = (to) => {
    const from = manifestDir.split("/").filter(Boolean);
    const target = to.split("/").filter(Boolean);
    let i = 0;
    while (i < from.length && i < target.length && from[i] === target[i]) i++;
    const up = from.length - i;
    const down = target.slice(i).join("/");
    return (up === 0 ? "./" : "../".repeat(up)) + down;
  };
  const code =
    `// AUTO-GENERATED by para-kit — the app-wide §13.8 server-source manifest.\n` +
    `// One import per emitted artifact; the flat list feeds createServerSourceHost.\n` +
    entries.map((e, i) => `import { __paraServerSources as __s${i} } from "${rel(e.artifact)}";`).join("\n") +
    (entries.length > 0 ? "\n\n" : "\n") +
    `export const serverSources = [${entries.map((_, i) => `...__s${i}`).join(", ")}];\n`;

  return { artifacts, manifest: { path: manifestPath, code }, diagnostics };
}

/**
 * The conventional sync endpoint route (written once if absent; the app owns
 * it afterward — INV-mpb-1 ejectability, not a regenerated boundary file).
 */
export function endpointTemplate() {
  return `// Written once by para-kit — the conventional Para sync endpoint. Yours to edit.
import { InProcessTransport } from "@lyku/para-sync";
import { createServerSourceHost, createSyncEndpoint } from "@lyku/para-kit";
import { serverSources } from "$lib/para-sync-manifest.js";

const transport = new InProcessTransport();
const host = createServerSourceHost(serverSources, { transport });
const endpoint = createSyncEndpoint({ transport, host });

export const GET = endpoint.GET;
export const POST = endpoint.POST;
`;
}
